#!/usr/bin/env sh

set -e

BUILD_DIR=`pwd`/build-dir
INSTALL_DIR=$1
ORIGINAL_DIR=`cat BUILD_DIR`

cp -rT ${BUILD_DIR} ${INSTALL_DIR}

find ${INSTALL_DIR}/conf -type f -print0 | xargs -0 sed -i -e "s,${ORIGINAL_DIR},${INSTALL_DIR},g"

